package org.jbomberman.model.listener;

public enum PackageType {
  LOADMAP,
  MOVE_PLAYER,
  SPAWN_BOMB,
  BOMB_EXPLOSION,
  TILE_DESTRUCTION,
  MOB_MOVEMENT,
  REMOVE_MOB,
  PLAYER_LIVES_UPDATE,
  PLAYER_INITIAL_POSITION,
  MOB_INITIAL_POSITION,
  SPAWN_POWERUP,
  POWERUP_APPLICATION,
  POWERUP_DESPAWN,
  PLAYER_SCORE_UPDATE,
  DRAW_PLAYER_LIVES_UPDATE
}
